__author__ = 'Андрей'

from pygame.locals import USEREVENT

END_SCENE =  USEREVENT + 1
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 840
PLATFORM_WIDTH = int(WINDOW_WIDTH/40)
PLATFORM_HEIGHT = int(WINDOW_WIDTH/40)
PLAYER_WIDTH = int(WINDOW_WIDTH/30)
PLAYER_HEIGHT = int(WINDOW_WIDTH/30)
MOVE_SPEED = 7
JUMP_POWER = 10
GRAVITY = 0.35
JUMP_POWER = 10
GRAVITY = 0.35
